#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01).
  domain information (){
	line =$(dig "$2$,$1$ | grep -A 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' '')
	# extract relevant information and print
	echo "$2 $line" | awk '(print "The subdomain" $1 " is a "$2" record and points to "$3)'

}

if [ "$#" ==1 ]
then
	domain_information "$1" "www"
	domain_information "$1" "lb-01"
	domain_information "$1" "web-01"
	domain_informattion "$1" "web-02"
elif ["$#" ==2]
then

_	domain_information "$1" "$2"
fi 
