#!/usr/bin/env bash
# Displays information about subdomains.

# variables & parameters
subdomains=("www" "lb-01" "web-01" "web-02")
domain="$1"
sub="$2"

dig_cmd() {
    sub="$2"
    INFO=$(dig +short "$sub.$domain")
    echo -e "The subdomain $sub is a A record and points to $INFO"
}

if [ $# -eq 1 ]; then
    for subs in "${subdomains[@]}"; do
        dig_cmd "$domain" "$subs"
    done
elif [ $# -eq 2 ]; then
    dig_cmd "$domain" "$sub"
fi
