#!/usr/bin/env bash
# Function to retrieve domain information
domain_information() {
    line=$(dig "$2.$1" | grep -A 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' '')
    # Extract relevant information and print
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
fi

