#!/usr/bin/env bash
#update/installation

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

#configure

sudo sh -c 'echo "server{
	listen 80;
	listen [::]:80;
	root/var/www/html;
	index index.html index.htm index.nginx-debian.html;
	
	sever_name_;
	
	location /{
		return 200 "hello world!//n";
	}
} >" etc/nginx/sites-available/default'
	
	sudo service nginx restart

	if sudo service nginx status |grep -q "active (running)";then
		echo "Nginx is running"
	else
		echo "Error:Nginx is not running"
	fi

