#!/usr/bin/env bash
# update/installation

# Update package information
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Start Nginx service
sudo service nginx start

# Configure Nginx default site
sudo sh -c 'echo "
server {
    listen 80 default_server;
    listen [::]:80 default;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        return 200 \"Hello World!\\n\";
    }
}
" > /etc/nginx/sites-available/default'

# Restart Nginx to apply changes
sudo service nginx restart
