#!/usr/bin/env bash
#update/installation


	sudo pt-get -y update
	sudo apt-get -y install nginx
	sudo service nginx start

	sudo sh -c 'echo "server {
		listen 80 default_server;
		listen [::]:80 default;
		root /var/www/html;
		index index.html index.htm index .nginx-debian.html;

		server_name_;

		location / {
			return 200 \"Hello World!\n\";
		}
	} "> /etc/nginx/sites-available/default'

	sudo service nginx restart;
