#!/usr/bin/env bash
# Update package information
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    server_name _;

    location /redirect_me {
        rewrite ^/redirect_me https://www.youtube.com/ permanent;
    }

    # Additional server configurations can be added here if needed
}
EOF'

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo service nginx restart

