#!/usr/bin/env bash
# Update package list

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo tee -a /etc/nginx/nginx.conf <<EOF
http {
    add_header X-Served-By $HOSTNAME;

    server {
        listen 80;
        location / {
            return 200 "Hello World!";
        }

        location /redirect_me {
            return 301 /;
        }

        error_page 404 /404.html;
        location = /404.html {
            return 404 "Ceci n'est pas une page";
        }
    }
}
EOF

# Restart Nginx to apply changes
sudo service nginx restart
