#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
# Add HAProxy PPA
sudo apt-get -y update
sudo add-apt-repository -y haproxy

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver web-01 54.89.29.95:80 check\n\tserver web-02 54.172.162.183:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
