#!/usr/bin/env bash
# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL

frontend webapp
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server 246582-web-01 100.24.235.13:80 check
    server 246582-web-02 54.144.138.199:80 check
EOL

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

echo "HAProxy has been installed and configured successfully."
