#!/usr/bin/env bash
# Script that displays numbers from 1 to 20 and:
# - Displays "bad luck from China" for the 4th loop iteration
# - Displays "bad luck from Japan" for the 9th loop iteration
# - Displays "bad luck from Italy" for the 17th loop iteration
# - Displays "Best School" for all other iterations

counter=0
while [ "$counter" -le 20 ]; 
do
    case "$counter" in
        4)
	    echo 
            echo "bad luck from China"
  
            ;;
        9)
            echo "bad luck from Japan"
            
            ;;
        17)
            echo "bad luck from Italy"
            
            ;;
        *)
            echo "Best School"
            ;;
    esac
    ((counter++))
done
